import { readdirSync, readFileSync, writeFileSync, mkdirSync, existsSync } from 'fs';
import { resolve, dirname, relative } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const siteDir = resolve(__dirname, '_site');
const outPath = resolve(__dirname, '_site', 'sw.js');

function getFiles(dir, base) {
  const results = [];
  if (!existsSync(dir)) return results;
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = resolve(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...getFiles(full, base));
    } else {
      const rel = '/' + relative(base, full).replace(/\\/g, '/');
      results.push(rel);
    }
  }
  return results;
}

function buildSW() {
  if (!existsSync(siteDir)) {
    console.error('❌ _site directory not found. Run Eleventy first.');
    process.exit(1);
  }

  const files = getFiles(siteDir, siteDir);

  const sw = `// Auto-generated by build-sw.mjs — do not edit
const CACHE_NAME = 'pioneer-web-v1';
const PRECACHE = ${JSON.stringify(files, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) => cache.addAll(PRECACHE)).catch((err) => {
      console.warn('[sw] precache partial failure:', err);
    })
  );
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(names.filter((n) => n !== CACHE_NAME).map((n) => caches.delete(n)))
    )
  );
  self.clients.claim();
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((cached) => cached || fetch(event.request))
  );
});
`;

  writeFileSync(outPath, sw);
  console.log(`✅ Service worker generated with ${files.length} precached files`);
}

buildSW();
